name: club_api
description: Dart client SDK for programmatic access to club servers.
version: 0.1.0
homepage: https://club.birju.dev
repository: https://github.com/BirjuVachhani/club
issue_tracker: https://github.com/BirjuVachhani/club/issues

publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  club_core:
    path: ../club_core
  http: ^1.6.0
  http_parser: ^4.1.2
  crypto: ^3.0.7

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.0
