name: club_storage
description: Blob storage abstraction and filesystem implementation for club.
version: 0.2.0
homepage: https://club.birju.dev
repository: https://github.com/BirjuVachhani/club
issue_tracker: https://github.com/BirjuVachhani/club/issues
publish_to: none

environment:
  sdk: ^3.11.0

resolution: workspace

dependencies:
  club_core:
    path: ../club_core
  path: ^1.9.1
  crypto: ^3.0.7

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.0
