#!/usr/bin/env bash
# =============================================================================
# build-cli.sh — Build the club CLI and install it on the user's PATH.
#
# Usage:
#   ./scripts/build-cli.sh                 # build + install (version "dev")
#   ./scripts/build-cli.sh --no-install    # build only, leave artifact in build/
#   ./scripts/build-cli.sh --uninstall     # remove the installed binary
#
# Build tooling:
#   We use `dart build cli` (the recommended Dart CLI builder, which
#   leverages build hooks). It produces a bundle directory:
#
#     build/cli/bundle/
#       bin/club            ← the executable
#       lib/<dynamic libs>  ← only present if the app uses native deps
#
#   The club CLI has no native dependencies, so only `bin/club` is
#   produced and the install can copy that single file.
#
# Versioning:
#   The script burns a development version into the binary using the
#   format:
#
#       <pubspec-version>-<short-sha>.dev      (e.g. 1.0.0-9c4f1e2.dev)
#
#   Pubspec version comes from packages/club_cli/pubspec.yaml; short sha
#   from `git rev-parse --short HEAD`. If the working tree isn't a git
#   repo the sha portion falls back to "local". The .dev suffix makes
#   it obvious in `club --version` that this is not a tagged release.
#
#   `dart build cli` is in preview and does not yet accept --define, so
#   the script writes the resolved version into
#   packages/club_cli/lib/src/version.dart, builds, then restores the
#   original file so your working tree is left clean.
#
# Install location:
#   $HOME/.local/bin/club (XDG-style; works without sudo).
#   The script warns if that directory is not yet on your PATH and prints
#   the one-liner to add to your shell rc.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Defaults ─────────────────────────────────────────────────────────────
INSTALL=true
UNINSTALL=false
INSTALL_DIR="${HOME}/.local/bin"
BUILD_DIR="${PROJECT_ROOT}/build/cli"
ENTRY="${PROJECT_ROOT}/packages/club_cli/bin/club.dart"

# ── Parse args ───────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-install)
      INSTALL=false
      shift
      ;;
    --uninstall)
      UNINSTALL=true
      shift
      ;;
    --install-dir)
      INSTALL_DIR="${2:?--install-dir requires a value}"
      shift 2
      ;;
    -h|--help)
      sed -n '2,/^# ====/p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      echo "Run with --help for usage." >&2
      exit 2
      ;;
  esac
done

# ── Uninstall path ───────────────────────────────────────────────────────
if [[ "$UNINSTALL" == "true" ]]; then
  if [[ -e "${INSTALL_DIR}/club" ]]; then
    rm -f "${INSTALL_DIR}/club"
    echo "Removed ${INSTALL_DIR}/club"
  else
    echo "Nothing to remove at ${INSTALL_DIR}/club"
  fi
  exit 0
fi

# ── Sanity check ─────────────────────────────────────────────────────────
if ! command -v dart >/dev/null 2>&1; then
  echo "Error: dart is not on your PATH." >&2
  exit 1
fi

cd "$PROJECT_ROOT"

# Make sure deps are resolved before trying to compile.
dart pub get >/dev/null

# ── Resolve dev version ──────────────────────────────────────────────────
# Format: <pubspec-version>-<short-sha>.dev
PUBSPEC="${PROJECT_ROOT}/packages/club_cli/pubspec.yaml"
PUBSPEC_VERSION="$(awk '/^version:/ {print $2; exit}' "$PUBSPEC")"
if [[ -z "$PUBSPEC_VERSION" ]]; then
  echo "Error: could not read version from $PUBSPEC" >&2
  exit 1
fi

if SHORT_SHA="$(git -C "$PROJECT_ROOT" rev-parse --short HEAD 2>/dev/null)"; then
  :
else
  # Not a git checkout — fall back to a placeholder so the build still
  # produces a meaningful version string.
  SHORT_SHA="local"
fi

VERSION="${PUBSPEC_VERSION}-${SHORT_SHA}.dev"
# Reject anything that contains shell-special characters; the resolved
# version is interpolated into a generated Dart file below.
if ! echo "$VERSION" | grep -Eq '^[A-Za-z0-9._+-]+$'; then
  echo "Refusing to use unsafe version string: $VERSION" >&2
  exit 1
fi

# ── Patch version.dart, build, restore ───────────────────────────────────
VERSION_FILE="${PROJECT_ROOT}/packages/club_cli/lib/src/version.dart"
ORIGINAL_VERSION_FILE="$(mktemp)"
cp "$VERSION_FILE" "$ORIGINAL_VERSION_FILE"

# Always restore the original on exit, even if the build fails. Leaving
# the working tree clean is important because the version constant lives
# in committed source.
cleanup() {
  if [[ -f "$ORIGINAL_VERSION_FILE" ]]; then
    cp "$ORIGINAL_VERSION_FILE" "$VERSION_FILE"
    rm -f "$ORIGINAL_VERSION_FILE"
  fi
}
trap cleanup EXIT

cat > "$VERSION_FILE" <<EOF
// GENERATED by scripts/build-cli.sh — restored to source after build.
// ignore_for_file: prefer_const_declarations
const String clubCliVersion = '${VERSION}';
EOF

# ── Build ────────────────────────────────────────────────────────────────
# Wipe any previous bundle so a stale lib/ from a different build doesn't
# linger alongside a new bin/.
rm -rf "${BUILD_DIR}/bundle"

echo "Building club CLI with \`dart build cli\`..."
echo "  entry:   ${ENTRY#${PROJECT_ROOT}/}"
echo "  output:  ${BUILD_DIR#${PROJECT_ROOT}/}/bundle/"
echo "  version: ${VERSION}"
echo ""

dart build cli \
  --target "$ENTRY" \
  --output "$BUILD_DIR"

BUNDLE_BIN="${BUILD_DIR}/bundle/bin/club"
BUNDLE_LIB="${BUILD_DIR}/bundle/lib"

if [[ ! -x "$BUNDLE_BIN" ]]; then
  echo "Error: expected executable not found at ${BUNDLE_BIN}" >&2
  exit 1
fi

echo ""
echo "Built: ${BUNDLE_BIN}"

# ── Install ──────────────────────────────────────────────────────────────
if [[ "$INSTALL" != "true" ]]; then
  echo ""
  echo "Skipping install (--no-install)."
  echo "Run the binary directly: ${BUNDLE_BIN}"
  exit 0
fi

mkdir -p "$INSTALL_DIR"

# If a bundle/lib/ exists (i.e. the app picked up native deps in the
# future) we cannot just copy the binary in isolation — install the
# whole bundle to $HOME/.local/share/club/ and point a wrapper at it.
# Today there are no native deps, so the simple copy is correct; the
# branch below is here to keep the script future-proof.
if [[ -d "$BUNDLE_LIB" ]] && [[ -n "$(ls -A "$BUNDLE_LIB" 2>/dev/null)" ]]; then
  SHARE_DIR="${HOME}/.local/share/club"
  mkdir -p "$SHARE_DIR"
  rm -rf "${SHARE_DIR}/bundle"
  cp -R "${BUILD_DIR}/bundle" "${SHARE_DIR}/bundle"
  cat > "${INSTALL_DIR}/club" <<EOF
#!/usr/bin/env bash
# Wrapper for the club CLI bundle (installed by scripts/build-cli.sh).
exec "${SHARE_DIR}/bundle/bin/club" "\$@"
EOF
  chmod +x "${INSTALL_DIR}/club"
  echo "Installed bundle to: ${SHARE_DIR}/bundle"
  echo "Wrapper at:          ${INSTALL_DIR}/club"
else
  cp "$BUNDLE_BIN" "${INSTALL_DIR}/club"
  chmod +x "${INSTALL_DIR}/club"
  echo "Installed to: ${INSTALL_DIR}/club"
fi

# ── PATH check ───────────────────────────────────────────────────────────
case ":${PATH}:" in
  *":${INSTALL_DIR}:"*)
    echo ""
    echo "✓ ${INSTALL_DIR} is already on your PATH."
    echo "  Try:  club --version"
    ;;
  *)
    echo ""
    echo "⚠  ${INSTALL_DIR} is NOT on your PATH yet."
    echo ""
    case "${SHELL:-}" in
      */zsh) RC_FILE="$HOME/.zshrc"; SHELL_NAME="zsh" ;;
      */bash) RC_FILE="$HOME/.bashrc"; SHELL_NAME="bash" ;;
      */fish) RC_FILE="$HOME/.config/fish/config.fish"; SHELL_NAME="fish" ;;
      *) RC_FILE="your shell's rc file"; SHELL_NAME="" ;;
    esac
    if [[ "$SHELL_NAME" == "fish" ]]; then
      echo "  Add to ${RC_FILE}:"
      echo "      fish_add_path \"${INSTALL_DIR}\""
    else
      echo "  Add to ${RC_FILE}:"
      echo "      export PATH=\"${INSTALL_DIR}:\$PATH\""
    fi
    echo ""
    echo "  Then restart your shell, or run:"
    echo "      export PATH=\"${INSTALL_DIR}:\$PATH\""
    echo ""
    echo "  After that, verify with:  club --version"
    ;;
esac
