name: club_cli
description: CLI tool for club server interaction.

version: 0.8.1

homepage: https://club.birju.dev
repository: https://github.com/BirjuVachhani/club
issue_tracker: https://github.com/BirjuVachhani/club/issues

publish_to: none

environment:
  sdk: ^3.13.0

resolution: workspace

dependencies:
  club_api:
    path: ../club_api
  analyzer: ^14.4.0
  ansicolor: ^2.0.3
  args: ^2.7.0
  collection: ^1.19.1
  crypto: ^3.0.7
  dart_mcp: ^0.5.2
  glob: ^2.2.0
  html: ^0.15.7
  path: ^1.9.1
  pub_semver: ^2.2.1
  pubspec_parse: ^1.6.0
  stream_channel: ^2.1.4
  tar: ^2.0.2
  yaml: ^3.1.4
  yaml_edit: ^2.2.4
  json_annotation: ^4.12.0
  equatable: ^2.1.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.32.0
  build_runner: ^2.16.1
  json_serializable: ^6.14.1

executables:
  club: club
